### ISSUE TITLE
Emacs 28.0.50 server prompt

### ISSUE THREAD

**Issue by pbeliveau** [kiennq/scoop-misc#2]
Not linked to the scoop .json manifest but rather if you can repeat the issue I have with the jump from 27.1 to 28.0.50.
When I start the daemon from powershell/cmd, the prompt for opening files, changing buffer, etc. is in the terminal instead of being in the GUI. Is this an isolated situation or can you reproduce the same issue?
![2020-07-01 20_51_19-PowerShell Core](https://user-images.githubusercontent.com/9312223/86304546-2750e180-bbdd-11ea-8e63-83f7df4c53e3.png)

**Comment by kiennq** [comment]
I haven't encounter this, I guess mainly due to I'm using `runemacs` to not block terminal.
And this seems to be Emacs problem, can you try to `cd` to `$env:scoop\apps\emacs-snapshot\current\bin\` and run the `emacs` binary from there directly to see if the problem repro'd?

Alternatively, you can just use `runemacs --daemon` or `emw`

**Comment by pbeliveau** [comment]
Running both `runemacs.exe --daemon` and `emw.exe` from the scoop directory worked (and outside of it).
This seems to be limited to starting emacs with the emacs.exe binary with the daemon switch.

Thanks for the help. I will close since runemacs works.
