### ISSUE TITLE
"Can't shim 'bin\runemacs.exe': File doesn't exist." when install emacs-snapshot

### ISSUE THREAD

**Issue by pinacle2000** [kiennq/scoop-misc#9]
I used scoop to insatll this emacs 28 version from your bucket and it had been working well with doom emacs. Then I tried to use your emacs 29, i.e. emacs-k. It worked fine but now I cann't make doom working. Since doom claimed 29 is not supported, I tried to switch back to 28. Now the issue comes:

1. scoop uninstall emacs-k
works.
2. scoop install emacs-snapshot
got error:
`Creating shim for 'runemacs'.`
`Can't shim 'bin\runemacs.exe': File doesn't exist.`

I tested emacs-k installation, and it works fine:
1.  scoop uninstall emacs-snapshot
works
2. scoop install emacs-k
works

**Comment by kiennq** [comment]
I think you're better to use the official version https://github.com/ScoopInstaller/Extras/blob/master/bucket/emacs.json instead of this emacs-snapshot, which is both 1) buggy 2) older version than the official one.
I will probably remove the emacs-snapshot from my scoop bucket soon since it doesn't server its purpose anymore.

**Comment by pinacle2000** [comment]
got it, thx!
